main/carriers/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, re_path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'carriers'

urlpatterns = [
    path('add-trailer-type/', views.CreateTrailerTypeView.as_view(), name='add_trailer_type'),
    path('add-trailer-brand/', views.CreateTrailerBrandView.as_view(), name='add_trailer_brand'),
    path('add-vehicle-type/', views.CreateVehicleTypeView.as_view(), name='add_vehicle_type'),
    path('add-vehicle-colour/', views.CreateVehicleColourView.as_view(), name='add_vehicle_colour'),
    path('add-wheel-formula/', views.CreateWheelFormulaView.as_view(), name='add_wheel_formula'),
    path('add-carrier-type/', views.CreateCarrierTypeView.as_view(), name='add_carrier_type'),
    path('add-organizational-type/', views.CreateOrganizationalTypeView.as_view(), name='add_organizational_type'),
    path('add-driver/', views.CreateDriverView.as_view(), name='add_driver'),
    path('add-vehicle/', views.CreateVehicleView.as_view(), name='add_vehicle'),
    path('add-carrier/', views.CreateCarrierView.as_view(), name='add_carrier'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('', views.index, name='index'),
]

# urlpatterns = [
#     # /carriers/
#     path('', views.CarrierListView.as_view(), name='index'),
#     # /carriers/5/
#     path('<int:pk>/', views.DetailView.as_view(), name='detail'),
#     # /carriers/5/results/
#     path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
#     # /carriers/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

main/main/urls.py
# -*- coding: utf-8 -*-

"""main URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carriers.urls'))
]

main/templates/project/basic.html
{# импорты bootstrap, js, Jquery для всего проекта #}

<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>{% block title %}Перевозчики{% endblock %} :: Логист</title>
  </head>
  <body>
    {% include 'project/navbar.html' %}
    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/project/navbar.html
<nav class="navbar navbar-light navbar-expand-md navbar-fixed-top navigation-clean-button"
     style="background: rgb(34,34,34);border-radius: 20;border-top-left-radius: 20;
     border-top-right-radius: 20;border-bottom-right-radius: 20;border-bottom-left-radius: 20;
     border-style: none;padding-top: 0;padding-bottom: 10px;">
    <div class="container">
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1">
            <span class="visually-hidden">Toggle navigation</span>
            <span class="navbar-toggler-icon"></span>
        </button>
        <div><a class="navbar-brand" href="#"><span>Creativarian </span> </a></div>
        <div class="collapse navbar-collapse" id="navcol-1" style="color: rgb(255,255,255);">
            <ul class="navbar-nav nav-right">
                <li class="nav-item"><a class="nav-link active" href="#" style="color: rgba(224,217,217,0.9);">Главная </a></li>
                <li class="nav-item dropdown">
                    <a class="dropdown-toggle nav-link" aria-expanded="false"
                       data-bs-toggle="dropdown" href="#" style="color: rgba(224,217,217,0.9);">База
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'carriers:index' %}">Мои Перевозчики</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_carrier' %}">Добавить Перевозчика</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_vehicle' %}">Добавить Транспортное средство</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_driver' %}">Добавить Водителя</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_organizational_type' %}">+ ОПФ</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_carrier_type' %}">+ Тип перевозчика</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_wheel_formula' %}">+ Колесная формула</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_vehicle_colour' %}">+ Цвет ТС</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_vehicle_type' %}">+ Тип ТС</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_trailer_brand' %}">+ Марка прицепа</a>
                        <a class="dropdown-item" href="{% url 'carriers:add_trailer_type' %}">+ Тип прицепа</a>
                    </div>
                </li>
                <li class="nav-item"><a class="nav-link" href="#" style="color: rgba(224,217,217,0.9);">Календарь </a></li>
                <li class="nav-item"><a class="nav-link" href="#" style="color: rgba(224,217,217,0.9);">FAQ </a></li>
                <li class="nav-item"><a class="nav-link" href="#" style="color: rgba(224,217,217,0.9);">Контакты </a></li>
            </ul>
            <p class="ms-auto navbar-text actions">
                <a class="login" href="{% url 'carriers:login' %}" style="color: rgba(224,217,217,0.9);">Авторизация</a>
                <a class="btn btn-light action-button" role="button" href="{% url 'carriers:registration' %}"
                   style="color: rgba(0,0,0,0.9);background: var(--bs-gray-200);border-radius: 10px;
                   border-style: solid;border-color: rgba(0,0,0,0.9;font-size: 16px;padding: 5px 8px;)">Регистрация</a>
            </p>
        </div>
    </div>
</nav>